### ISSUE TITLE
SendJsonResponse doesn't handle UTF-8

### ISSUE THREAD

**Issue by omegavesko** [sukona/GrapevinePlus#2]
The following code doesn't respect the encoding:

    context.Response.ContentEncoding = Encoding.UTF8;
    this.SendJsonResponse(context, json);

However, rendering the JSON to text manually and sending it as plain text works fine:

    this.SendTextResponse(context, json.ToString(), Encoding.UTF8);

**Comment by scottoffen** [comment]
UTF8 is now the default encoding for JSON, but it will only be set as such if the ContentEncoding on the Response object was not set before calling SendJsonResponse.
